language: python

cache: pip

python:
- '3.5'
- '3.6'
- 'nightly'  # currently 3.7

matrix:
  allow_failures:
  - python: 'nightly'

#env:
#- DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
#services:
#- docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5

install:
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- gcc -v
#- docker pull $DOCKER_IMAGE
- pip freeze
- make download-test-files

script:
- make test
- make lint
- ./tests/check_tag.py
# TODO manylinux is currently broken as gcc-5 isn't available on centos 5
#- docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/tests/build-wheels.sh

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: samuelcolvin
  password:
    secure: Qrh0eve9uLknhDZ7q5DQaSNaL8gG/9bXaYAjJB3s9hMAXtTM+4zVBpke0Dl5Hziy0sWN304OSuAwHSzzBaZxChZ9mpaE7cuuEVNo5RZXNZJxbsHQLlTngV1w6khd7VhgmgG6QbYqoFXgpkB3p88bLxyAc4I2PbTVY4omeRCzKg8av20pu+C3mCN0e5dvE7u2CFDgd/s0V4fgt0Cjhw88sS/7fqsUZpbXy8J9Q+V1IP40CAmr8nXPEva4nSmTOFEyt6NOijWWizea5LvT9MJwK7tugM6BeH4IT1OaA58eRuOlDenaTDbhfOMQain/PTEWwr3KnYa8v6dvaVSU2uMEm2v+hVCYqQeFwAdFEJLY/bpl5kTRQ++dmvEPrWdU0cOf22vDzjfLLSHtWRQqtfp5BXpfL7jXV2IydUTjEmrybok7LxoRc7JhrfvlAScd6t2R/OQ1dyvav68ICkOfAu660h9ETa0wsq917wIj9kErz4Gj+ItLwHsRkCwoEKpk3Xa+FkUkuEMoD/gmPB93R5fpSldc0ZCNXzNPcWJcBWxQpvlhXs/lhdl5gG15BUzDYQbWsK7XaGn8wV+cHNODee4VE/vKUTlo/xNWkxmWMWzQS7t+yZhmorN69Xd4wGcvT2Bed/9Q/bc154G2da+ps89cWVkRgY2lYrYXcu1FM7O9KMs=
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  skip_cleanup: true
  on:
    tags: true
    python: 3.6
